version: '3'

services:
  clipping-cpython:
    build:
      context: .
      args:
        - IMAGE_NAME=${CPYTHON_IMAGE_NAME}
        - IMAGE_VERSION=${CPYTHON_IMAGE_VERSION}
    image: lycantropos/clipping-cpython:4.1.0-alpha
    volumes:
      - ./clipping:/opt/clipping/clipping
      - ./pytest.ini:/opt/clipping/pytest.ini
      - ./README.md:/opt/clipping/README.md
      - ./requirements-tests.txt:/opt/clipping/requirements-tests.txt
      - ./requirements.txt:/opt/clipping/requirements.txt
      - ./setup.py:/opt/clipping/setup.py
      - ./tests:/opt/clipping/tests
    entrypoint: pytest
