version: '3'

services:
  clipping-pypy:
    build:
      context: .
      args:
        - IMAGE_NAME=${PYPY_IMAGE_NAME}
        - IMAGE_VERSION=${PYPY_IMAGE_VERSION}
    image: lycantropos/clipping-pypy:6.0.0-alpha
    volumes:
      - ./clipping:/opt/clipping/clipping
      - ./pyproject.toml:/opt/clipping/pyproject.toml
      - ./README.md:/opt/clipping/README.md
      - ./setup.py:/opt/clipping/setup.py
      - ./tests:/opt/clipping/tests
    entrypoint: pytest
