version: '3'

services:
  clipping-cpython:
    build:
      context: .
      args:
        - IMAGE_NAME=${CPYTHON_IMAGE_NAME}
        - IMAGE_VERSION=${CPYTHON_IMAGE_VERSION}
    image: lycantropos/clipping-cpython:5.1.2
    volumes:
      - ./clipping:/opt/clipping/clipping
      - ./pyproject.toml:/opt/clipping/pyproject.toml
      - ./README.md:/opt/clipping/README.md
      - ./setup.py:/opt/clipping/setup.py
      - ./tests:/opt/clipping/tests
    entrypoint: pytest
